### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by patriciachrysy** [ABDULALI3468/space-travelers-hub#25]
We created the repo and setup the Kanban board. 
- Here is the link to github project: [Github Project](https://github.com/ABDULALI3468/space-travelers-hub/projects/1)
- We are two people working on this project: [Abdul Ali](https://github.com/ABDULALI3468) and [I, Manezeu Patricia](https://github.compatriciachrysy)

Thanks for checking

**Comment by RolandM99** [comment]
Hello **Team** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌

- [ ] You have submitted a project, that doesn't fit the core requirements. Kindly, make sure that your comment contains:
- link to your GitHub project
- information about the number of people in your group

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by patriciachrysy** [comment]
I updated my comment, thanks for checking again

**Comment by rustam-tolipov** [comment]
Hi @patriciachrysy and @ABDULALI3468 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_


## Required Changes ♻️

- [x] You have set up the kanban board correctly 👏🏼. Your group includes two people so the number of cards should be equal to **17**. Please remove all cards with Team3 in the title
![image](https://user-images.githubusercontent.com/69011963/179736248-6127aa9f-2222-4226-9626-f2de90f59f5f.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by patriciachrysy** [comment]
Removed all the dragon cards from the Kanban since we are only 2 in the team

**Comment by VICTOR-CHUKWU** [comment]
Hi Team, 
# STATUS: APPROVED! 🥇 💯 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
